### ISSUE TITLE
Malformed error message on validation failure

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-providers-openstack#455]
When validation failed for an openstack provider, I got a rather gnarly error message:

![image](https://user-images.githubusercontent.com/78529/55015608-89c33700-4fc3-11e9-850e-3223273282a2.png)

Originally posted at https://github.com/ManageIQ/manageiq-ui-classic/issues/5320

I think specifically it's when you try to enable SSL but the server doesn't support, though I've not tried all the combinations.

**Comment by agrare** [comment]
@djberg96 can you find a backtrace from the logs?

**Comment by mansam** [comment]
That looks like a 404 page from the web server due to trying to hit the SSL endpoint that doesn't exist. You could get a message like that from putting in any number of hosts with listening services that aren't Openstack services. I'll look into cleaning up how we deal with HTTP errors that we don't expect.

**Comment by djberg96** [comment]
Fixed via https://github.com/ManageIQ/manageiq-providers-openstack/pull/456. Thanks @mansam!
